--liquibase formatted sql
--changeset abhishek.8in@gmail.com:1.0.0
CREATE TABLE LINKS (
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    UUID VARCHAR(36),
    TENANT VARCHAR(32),
    CODE VARCHAR(16),
    URL VARCHAR(8000) CHARACTER SET 'ascii' COLLATE 'ascii_general_ci',
    EXPIRY DATETIME,
    STATUS SMALLINT,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP

);